default:
  image: node:latest

variables:
  VERCEL_ORG_ID: $ORG_ID
  VERCEL_PROJECT_ID: $PROJECT_ID

stages:
  - analyze
  - deploy

before_script:
  - npm install -g vercel
  - npm install -g sonarqube-scanner

analyze:
  stage: analyze
  script:
    - >
      npm install

      npm run test:cov

      sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY
      -Dsonar.sources=.
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_LOGIN
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      -Dsonar.testExecutionReportPaths=reports/test-report.xml
      -Dsonar.genericcoverage.unitTestReportPaths=reports/test-report.xml
      -Dsonar.coverage.exclusions=**/*spec.ts
  only:
    - main
    - staging

deploy:
  stage: deploy
  script:
    - >
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        echo "Deploying to Production"
        vercel --prod --confirm -t $VERCEL_TOKEN --scope $VERCEL_ORG_ID
      elif [ "$CI_COMMIT_BRANCH" = "staging" ]; then
        echo "Deploying to Staging"
        vercel --confirm -t $VERCEL_TOKEN --scope $VERCEL_ORG_ID
      else
        echo "Non-production or staging branch, skipping deploy"
      fi
  only:
    - main
    - staging