default:
  image: node:latest

variables:
  VERCEL_ORG_ID: $VERCEL_ORG_ID

stages:
  - sonarqube
  - deploy

sonarqube:
  stage: sonarqube
  script:
    - npm install sonar-scanner
    - npm sonar-scanner \
        -Dsonar.projectKey=ppl-a2_talacare-be_AY13ZcUtk9qxTTGJICtq \
        -Dsonar.sources=.
        -Dsonar.host.url=https://sonarqube.cs.ui.ac.id \
        -Dsonar.login=0164738eaa81cebfe4f246b4df7f8a2cbb99f071

deploy:
  stage: deploy
  variables:
    VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
  script:
    - npm i -g vercel
    - vercel --confirm -t $VERCEL_TOKEN --prod
  only:
    - main