default:
  image: node:latest

variables:
  VERCEL_ORG_ID: $ORG_ID

stages:
  - analyze
  - deploy

before_script:
  - npm install -g vercel
  - npm install -g sonarqube-scanner

analyze:
  stage: analyze
  script:
    - >
      sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.sources=. 
      -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
  only:
    - main

deploy:
  stage: deploy
  variables:
    VERCEL_PROJECT_ID: $PROJECT_ID
  script:
    - vercel --confirm -t $VERCEL_TOKEN --prod

  only:
    - main
