default:
  image: node:latest

variables:
  VERCEL_ORG_ID: $VERCEL_ORG_ID

stages:
  - sonarqube
  - deploy

sonarqube:
  stage: sonarqube
  script:
    - npm install sonar-scanner
    - npm run sonar-scanner \
        -Dsonar.projectKey=$SONAR_PROJECT_KEY \
        -Dsonar.sources=.
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_LOGIN

deploy:
  stage: deploy
  variables:
    VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
  script:
    - npm i -g vercel
    - vercel --confirm -t $VERCEL_TOKEN --prod
  only:
    - main