name: CI

on:
  push:
    branches:
      - main
      - staging

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests and analyze
        run: |
          npm run test
          npm run test:cov
          sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_LOGIN \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.genericcoverage.testExecutionReportPaths=reports/test-report.xml \
            -Dsonar.coverage.exclusions=**/*spec.ts
      
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'

  deploy:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install vercel and sonarqube scanner
        run: |
          npm install -g vercel
          npm install -g sonarqube-scanner
      
      - name: Deploy to Production or Staging
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Deploying to Production"
            vercel --prod --confirm -t ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.ORG_ID }}
            echo "Setting alias for Production"
            vercel alias ${{ secrets.VERCEL_PRODUCTION_URL }} --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.ORG_ID }}
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            echo "Deploying to Staging"
            url=$(vercel --confirm -t ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.ORG_ID }} | grep "https://")
            echo "Setting alias for Staging"
            vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" api-talacare-staging.vercel.app --scope=${{ secrets.ORG_ID }}
          else
            echo "Non-production or staging branch, skipping deploy"
          fi
      
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
