name: SSH and Pull Docker Image

# Trigger on workflow_run completion of "Build and Push Docker Image"
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  ssh_and_pull:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Local Device and Pull Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no muflihmaxi@180.252.174.221 \
          "docker pull gansixeneh/talacare-nest:latest && \
           docker stop local-talacare-be && \
           docker rm local-talacare-be && \
           docker run -d --name local-talacare-be gansixeneh/talacare-nest:latest"
